name: taskmgr
description: 随随办办 / FlowDo — 无压力任务管理
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
